### ISSUE TITLE
🐛 after running check --apply, vue files become empty

### ISSUE THREAD

**Issue by Jungzl** [biomejs/biome-intellij#50]
### Environment information

```block
CLI:
  Version:                      1.7.0
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           windows

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         unset
  JS_RUNTIME_VERSION:           "v20.12.1"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### What happened?

![image](https://github.com/biomejs/biome/assets/35426360/8794efdf-25d7-4b60-b205-c1261b94efd8)

https://github.com/biomejs/biome/assets/35426360/ca316758-b67a-4d05-ba40-c347730c4d1b

### Expected result

It should works as usual

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by kujtimiihoxha** [comment]
Seeing the same issue also

**Comment by tasshi-me** [comment]
Hello, there!
I see the same issue with Astro files.

This issue seems to be caused by https://github.com/biomejs/biome/issues/2225.
For Vue or Astro files, the biome CLI with the `--stdin-file-path` option will output nothing with a zero status code.
This plugin writes the output of the CLI command, so the src file is overwritten by empty string.

## Reproduction

I enabled only the "Run safe fixes on save" option.

This plugin runs biome CLI inside, so I tried a command that is [generated by this plugin](https://github.com/biomejs/biome-intellij/blob/062f0fdde7aa32d57ebfeb18c6bb42877a69b5a7/src/main/kotlin/com/github/biomejs/intellijbiome/BiomeStdinRunner.kt#L22) on my local shell.
The result of this command is written to the src file.

```
$ [node path] [biome path] check --stdin-file-path [src path] --formatter-enabled=false --apply --config-path [config path]
```

This plugin [passes the source code to the stdin of the above command.](https://github.com/biomejs/biome-intellij/blob/062f0fdde7aa32d57ebfeb18c6bb42877a69b5a7/src/main/kotlin/com/github/biomejs/intellijbiome/BiomeStdinRunner.kt#L66)

```
$ cat [src path] | [node path] [biome path] check --stdin-file-path [src path] --formatter-enabled=false --apply --config-path [config path]
```

### For a TypeScript (`.ts`) file

It prints formatted code. The status code is zero.

```shell
$ cat /path/to/project/src/consts.ts |\
    /Users/user/.nodenv/shims/node \
    /path/to/project/node_modules/@biomejs/biome/bin/biome check \
    --stdin-file-path /path/to/project/src/consts.ts \
    --formatter-enabled=false --apply \
    --config-path /path/to/project
... # (The formatted code is printed)

$ echo $?
0
```

### For a Astro (`.astro`) file

It prints nothing. The status code is zero.

```shell
$ cat /path/to/project/src/pages/index.astro |\
    /Users/user/.nodenv/shims/node \
    /path/to/project/node_modules/@biomejs/biome/bin/biome check \
    --stdin-file-path /path/to/project/src/pages/index.astro \
    --formatter-enabled=false --apply \
    --config-path /path/to/project
# (Nothing printed)

$ echo $?
0
```

**Comment by tasshi-me** [comment]
In the VSCode plugin, this issue does not happen because the architecture seems to be different.
(Sorry, I don't know well.)

- https://github.com/biomejs/biome-vscode/blob/b55af94cb26f4c86c2213db93ccf6982e17ec0e2/src/main.ts#L175
- https://speakerdeck.com/unvalley/typescript-linnting-and-formatting?slide=12
