### ISSUE TITLE
Only old version of plugin is available in latest IDEA version

### ISSUE THREAD

**Issue by APshenkin** [biomejs/biome-intellij#74]
After upgrading to 2024.2 IDEA reinstalls biome plugin to 1.0.0 version, removing all fixes introduced later

<img width="1046" alt="image" src="https://github.com/user-attachments/assets/44a734b5-bd01-4a41-9882-55387aac94a6">
Seems since 1.0.2 last version was hardened

**Comment by JamyGolden** [comment]
I have this issue too. I tried to install from a file on disk and got the following error: 

![image](https://github.com/user-attachments/assets/5f024e6d-ae84-45cb-a9f4-818baa480e2e)

Is the issue maybe happening because my build starts with `IU-*`

OS: PopOS `22.04` (Linux)
App: IntelliJ Idea Ultimate
Version: `2024.2.0.1`

**Comment by bc-m** [comment]
The IntelliJ IDEs from version 2024.2 requires IntelliJ Platform Gradle Plugin v2: https://plugins.jetbrains.com/docs/intellij/api-notable-list-2024.html

Migration guide: https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-migration.html

**Comment by frisksitron** [comment]
This is still an issue for the stable channel.

![image](https://github.com/user-attachments/assets/7eb6cc41-f453-4650-97d2-77550a5dea32)

I am currently using nightly through disk install.

![image](https://github.com/user-attachments/assets/710fb6b1-fe5c-4c22-9f86-189c7f9ad72d)

**Comment by ematipico** [comment]
I just published 1.3.0. It will take some time to get approved, usually two business days
